### ISSUE TITLE
Export cors headers

### ISSUE THREAD

**Issue by srzsh** [Kleak/shelf_helpers#3]
Export CORS header names as constants
(ex: `const CORSOrigin = 'Access-Control-Allow-Origin'`)

**Comment by kevin-sakemaer** [comment]
Would be better if we used the value from dart:io.

I will change that in an update.

**Comment by srzsh** [comment]
Can you point me to the documentation page? I can't find the header names for CORS in dart:io

**Comment by kevin-sakemaer** [comment]
Inside `HttpHeader` you have almost all the header.

**Comment by srzsh** [comment]
I thought I had missed it but no, HttpHeader does not export `Access-Control-Allow-Origin`

**Comment by kevin-sakemaer** [comment]
Made a PR on the sdk repos to add them :) 
https://github.com/dart-lang/sdk/pull/45947
